services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    SNDSABIN\ImportBundle\Command\:
        resource: '../../Command'
        public: true
        tags: ['console.command.service_arguments']

# add more services, or override services that need manual wiring
    SNDSABIN\ImportBundle\Helper\Config:
        public: true
        tags: ['config.helper']
        arguments:
            - "%import.config%"
    SNDSABIN\ImportBundle\Parser\CsvParser:
        public: true
        tags: ['csv_parser']
