import:
    config:
        base_directory: '' # base directory where all the files to be imported are located (required)
        customer:
            file: '' # file name (required)
            mapper: '' # required
            importer: '' # only required if other than base importer is to be used
