import:
    config:
        base_directory: '' # base directory where all the files to be imported are located (recommended)
        customer:
            file: '' # file name (recommended)
            importer: '' # only required if other than base importer is to be used
            mapper: '' # optional
